language: R
cache:
  - packages
  - ccache
latex: false
sudo: required
os: linux
dist: xenial

r:
  - release
  - oldrel

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
